### ISSUE TITLE
turnip ambiguos steps

### ISSUE THREAD

**Issue by eins78** [leihs/leihs-integration-tests#1]
```
 Turnip::Ambiguous:
       Ambiguous step definitions
         - "I am logged in successfully" (/home/ci-exec-user/.rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/turnip-3.1.0/lib/turnip/dsl.rb:10:in `step')
         - "I am logged in :subapp" (/home/ci-exec-user/.rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/turnip-3.1.0/lib/turnip/dsl.rb:10:in `step')
```

> https://ci.zhdk.ch/cider-ci/ui/workspace/trials/81d7e5d9-9637-4e1f-b45c-200f160cddb9/scripts/test#no-target

**Comment by eins78** [comment]
@nimaai sometimes this make the test run fail, sometimes not 🤷‍♂️
